### ISSUE TITLE
No Printers Available

### ISSUE THREAD

**Issue by MikeUSNRet** [jneilliii/OctoPrint-MyMiniFactory#11]
Have installed this but in the settings, there are no printers listed under the Printer Manufacturer dropdown box...  have tried to remove and re-install plugin, but still the same issue.   When I had an Ender 3, it appeared just fine.  Now have an Anycubic I3 Mega-S.

**Comment by jneilliii** [comment]
Any errors in the logs or the browser's developer console when you start up the site?

**Comment by MikeUSNRet** [comment]
There are no errors listed in any of the octoprint logs.   When I get to the myminifactory site via the plugin, this is displayed at the top of the page:

In order to utilize Click & Print services you must register your printer in settings.

yet when I go to settings, there are no selections to be made in the Printer Manufacturers dropdown box so I can get a QR code etc.
I have removed and re-installed several times now with no changes.

**Comment by jneilliii** [comment]
Thanks.  I just installed on a new instance and it appears MyMiniFactory changed the return results of the api call for printers list.  I just pushed a new branch that should resolve this.  If you don't mind testing for me that would be great.  You can install using the URL below in plugin manager.  

https://github.com/jneilliii/OctoPrint-MyMiniFactory/archive/0.1.4.zip

Once installed load the web site and then force a refresh once and I think that will get the list back.

**Comment by MikeUSNRet** [comment]
Looks like it is working correctly now.
