### ISSUE TITLE
QR not being generated

### ISSUE THREAD

**Issue by bruvv** [jneilliii/OctoPrint-MyMiniFactory#15]
I am missing my printer, it is a `creality Ender 3 Max` that is missing from the list. But as it is a `Ender 3 Pro`, I went ahead and selected that but the QR generator just keeps spinning:
![afbeelding](https://user-images.githubusercontent.com/3063928/135716041-16a94d3e-3ba8-4e8f-a515-33722a440522.png)

**Comment by jneilliii** [comment]
could you check your octoprint.log for errors please?

**Comment by bruvv** [comment]
![afbeelding](https://user-images.githubusercontent.com/3063928/135723037-58f7a841-871f-434d-8b27-9a52e9196cef.png)
There are no errors in the ocotoprint.log

**Comment by jneilliii** [comment]
Yeah, nothing really relevant there and it does appear to be loading the printer list from MyMiniFactory. Are there any errors in your browser's developer tools (typicall F12 on your keyboard) console tab when registering, and what browser are you using? I tried this last night and it worked for me without issue on a fresh install.

**Comment by bruvv** [comment]
I'm running octoprint in a docker container with home assistant as os. https://github.com/fredrikbaberg/hassio-addons (next version) I've used edge, Firefox on windows. Firefox on Android and home assistant app. I do use adguard. What URLs are used? Will see tomorrow if something comes up in the console.

**Comment by jneilliii** [comment]
So the pi will attempt to pull the mac address as an identifier and I wonder if this may not be working in your docker instance. I can test that on my end to see with a standard non HA docker server I have at the house. It will submit that to `https://www.myminifactory.com/api/v2/printer` then the URL to the QR code will be provided as part of the registration process with MyMiniFactory's servers. The url goes to `https://chart.googleapis.com/` plus the details for the QR code to be dynamically created.

**Comment by jneilliii** [comment]
I have confirmed, it works for me in my docker server.

**Comment by bruvv** [comment]
The docker that I'm using is a specific docker that is integrated into home assistant. Which docker are you using? And also what Mac address is it pulling, the docker host Mac ? Than that's the issue. Can I test a command that you're using to get the Mac to see if that's working in the docker at my end ?

**Comment by jneilliii** [comment]
you would have to start whichever shell you have access to for that container and activate the venv OctoPrint is installed in (unless it runs as root), and stary python, and then run these commands

```
from uuid import getnode as get_mac
mac_address = ':'.join(("%012X" % get_mac())[i:i+2] for i in range(0, 12, 2))
print(mac_address)
```

**Comment by bruvv** [comment]
Thanks. How can I see if it is running as root or in a venv? And if it is running in a venv how can I get into it? I'm not very used to work with virtual python environments.

**Comment by bruvv** [comment]
This is from the console when clicking on generate QR code:
```
POST http://192.168.2.3:5000/api/plugin/myminifactory 403 (Forbidden) @ packed_libs.js?86afb3b9:13
```
![afbeelding](https://user-images.githubusercontent.com/3063928/135745078-24f38c41-1bbe-4a05-a1d4-2b40a82cbd91.png)

**Comment by jneilliii** [comment]
I think so. Need to figure out if ha docker allows for access to the container from itself. Could be some kind of block to not allow loopback.

**Comment by bruvv** [comment]
Is there a way to do this manually in the mean time btw?

**Comment by jneilliii** [comment]
There's not any way I'm aware of.

**Comment by jneilliii** [comment]
So the meat of the registration process is [here](https://github.com/jneilliii/OctoPrint-MyMiniFactory/blob/492841544d459a32b1f1a5ad2eb7c1dbc8581cfe/octoprint_myminifactory/__init__.py#L146-L175). It uses uuid to generate a random serial number if it hasn't already been created in settings. It uses that and the mac address of the octoprint instance to submit a registration request to https://www.myminifactory.com/api/v2/printer with that information. If you change the logging settings for the plugin to debug, it should in theory log the information throughout the process.

**Comment by fredrikbaberg** [comment]
I'm still receiving a 403, but at least managed to get the log output (I've recently been informed about some issues with the previous version I published).

To give some information about the addon, it can be accessed through two different methods:
- Embedded in Home Assistant through something they call Ingress: https://developers.home-assistant.io/docs/add-ons/presentation/#ingress
- Expose the container directly to the network, e.g. through port 5000.

The second option should be close to what octoprint-docker uses, but for some reason it does not even work there. I suspect it is related to the reverse proxy configuration, but am not sure how to solve that - I'm currently using HAProxy, but a newer version than octoprint-docker so the reqrep commands won't work. The current `haproxy.cfg` is located at https://github.com/fredrikbaberg/hassio-addons/blob/bfc1f7ca24043dd2d0696d7c86d558fc8a248beb/octoprint-next-dev/rootfs/etc/haproxy/haproxy.cfg, not sure if you can see what I'm missing?

This is the log output I got, I set the MyMiniFactory plugin logger level to DEBUG and everything else to WARNING:

```
2021-10-07 13:47:02,279 - tornado.access - WARNING - 404 GET /plugin/myminifactory/static/css/plugin/myminifactory/static/images/myminifactory_logo_128.png (172.30.32.2) 15.42ms
2021-10-07 13:47:11,643 - tornado.access - WARNING - 404 GET /service-worker.js (172.30.32.1) 15.12ms
2021-10-07 13:47:21,212 - tornado.access - WARNING - 404 GET /plugin/myminifactory/static/css/plugin/myminifactory/static/images/myminifactory_logo_128.png (172.30.32.1) 11.34ms
2021-10-07 13:47:36,099 - tornado.access - WARNING - 403 POST /api/plugin/myminifactory (172.30.32.1) 4.73ms
2021-10-07 13:47:39,935 - tornado.access - WARNING - 404 GET /service-worker.js (172.30.32.1) 2.56ms

```

**Comment by jneilliii** [comment]
I was curious about that url path change. I don't use the plugin personally so just assumed you had tested before submitting a pr. I'll revert that change now.

**Comment by fredrikbaberg** [comment]
I think the user needs to be included in the group "users" (called "Operator" in UI), for some reason "admin" is not enough. I'll test it on a clean install after making that change to the CLI call.

**Comment by fredrikbaberg** [comment]
I've now verified that adding the user to group "users" (command adjusted to "--group users --group admins" instead of "--admin") solves the issue, the QR code is generated and visible.
