### ISSUE TITLE
Cant add DIY 3DPrinter

### ISSUE THREAD

**Issue by 2andr** [jneilliii/OctoPrint-MyMiniFactory#5]
How can i add DIY Printer in plugin?
In List of Printer model on MyMiniFactory site - i can choose DIY/Homemade
But not in List on plugin!
![2018-12-13_11-56-53](https://user-images.githubusercontent.com/6235964/49927254-88677600-fece-11e8-9c1d-86260244d339.png)

**Comment by jneilliii** [comment]
You'll need to email MyMiniFactory as described in the readme.
