### ISSUE TITLE
Gcode generated for Ender 3 is broken

### ISSUE THREAD

**Issue by mithunkr** [jneilliii/OctoPrint-MyMiniFactory#6]
I tried printing one object using the plugin, to my Ender 3 printer at home, that uses Klipper firmware on Octopi.
I got this error "`Unable to parse move 'N14 G1 Z15.0 F{travel_speed}*61'`"

Not sure what's this `F{travel_speed}` supposed to mean.

Here's the initial Gcode piece...

```
;FLAVOR:Marlin
;TIME:6666
;Filament used: 0m
;Layer height: 0.15

;Generated with Cura_SteamEngine master
M190 S50
M104 S215
M109 S215
M82 ;absolute extrusion mode
G21 ;metric values
 G90 ;absolute positioning
 M82 ;set extruder to absolute mode
 M107 ;start with the fan off
 G28 X0 Y0 ;move X/Y to min endstops
 G28 Z0 ;move Z to min endstops
 G1 Z15.0 F{travel_speed} ;move the platform down 15mm
 G92 E0 ;zero the extruded length
 G1 F200 E6 ;extrude 6 mm of feed stock
 G92 E0 ;zero the extruded length again
 G1 F{travel_speed}
 ;Put printing message on LCD screen
 M117 Printing...
G92 E0
G1 F2100 E-6
;LAYER_COUNT:343
;LAYER:-6
M107
```

**Comment by jneilliii** [comment]
That is an issue with the MyMiniFactory slicer and had nothing to do with the plugin. The plugin just downloads the gcode file from their service You may want to reach out to them. 

info@myminifactory.com
