### ISSUE TITLE
Plugin does not seem to work anymore

### ISSUE THREAD

**Issue by slock83** [jneilliii/OctoPrint-MyMiniFactory#7]
Hello,

As of today, it seems your plugin is now unfortunately broken :/
Here is the single line of log I was able to extract, probably something on MMF's end :
`2018-12-21 18:31:16,121 - octoprint.plugins.myminifactory - DEBUG - Received printers: {"total_count":593,"items":[{"id":732,"name":"2014 Series 1 3D printer","brand":null,"automatic_slicing":null,"nozzle_diameter":null,"premium":false,"model":"2014-series-1-3d-printer","image":null,"dimensions":{"x":null,"y":null,"z":null}},{"id":969,"name":"3 Axis CNC Milling machine","brand":null,"automatic_slicing":null,"nozzle_diameter":null,"premium":false,"model":"3-axis-cnc-milling-machine","image":null,"dimensions":{"x":null,"y":null,"z":null}},{"id":1021,"name":"3D Cloner DH","brand":null,"automatic_slicing":null,"nozzle_diameter":null,"premium":false,"model":"3d-cloner-dh","image":null,"dimensions":{"x":null,"y":null,"z":null}},{"id":1022,"name":"3D Cloner DH+","brand":null,"automatic_slicing":null,"nozzle_diameter":null,"premium":false,"model":"3d-cloner-dh+","image":null,"dimensions":{"x":null,"y":null,"z":null}},{"id":1018,"name":"3D Cloner DH+ 1st Gen","brand":null,"automatic_slicing":null,"nozzle_diameter":null,"premium":false,"model":"3d-cloner-dh+-1st-gen","image":null,"dimensions":{"x":null,"y":null,"z":null}},{"id":1023,"name":"3D Cloner DH+ 2","brand":null,"automatic_slicing":null,"nozzle_diameter":null,"premium":false,"model":"3d-cloner-dh+-2","image":null,"dimensions":{"x":null,"y":null,"z":null}},{"id":1019,"name":"3D Cloner ST","brand":null,"automatic_slicing":null,"nozzle_diameter":null,"premium":false,"model":"3d-cloner-st","image":null,"dimensions":{"x":null,"y":null,"z":null}},{"id":1020,"name":"3D Cloner ST+","brand":null,"automatic_slicing":null,"nozzle_diameter":null,"premium":false,"model":"3d-cloner-st+","image":null,"dimensions":{"x":null,"y":null,"z":null}},{"id":669,"name":"3D DLP Printer v2.0","brand":null,"automatic_slicing":null,"nozzle_diameter":null,"premium":false,"model":"3d-dlp-printer-v20","image":null,"dimensions":{"x":null,"y":null,"z":null}},{"id":991,"name":"3D Felix 1.0 Assembled Dual","brand":null,"automatic_slicing":null,"nozzle_diameter":null,"premium":false,"model":"3d-felix-10-assembled-dual","image":null,"dimensions":{"x":null,"y":null,"z":null}},{"id":988,"name":"3D Felix 1.0 Assembled Single","brand":null,"automatic_slicing":null,"nozzle_diameter":null,"premium":false,"model":"3d-felix-10-assembled-single","image":null,"dimensions":{"x":null,"y":null,"z":null}},{"id":985,"name":"3D Felix 1.0 Kit Dual","brand":null,"automatic_slicing":null,"nozzle_diameter":null,"premium":false,"model":"3d-felix-10-kit-dual","image":null,"dimensions":{"x":null,"y":null,"z":null}},{"id":982,"name":"3D Felix 1.0 Kit Single","brand":null,"automatic_slicing":null,"nozzle_diameter":null,"premium":false,"model":"3d-felix-10-kit-single","image":null,"dimensions":{"x":null,"y":null,"z":null}},{"id":990,"name":"3D Felix 2.0 Assembled Dual","brand":null,"automatic_slicing":null,"nozzle_diameter":null,"premium":false,"model":"3d-felix-20-assembled-dual","image":null,"dimensions":{"x":null,"y":null,"z":null}},{"id":987,"name":"3D Felix 2.0 Assembled Single","brand":null,"automatic_slicing":null,"nozzle_diameter":null,"premium":false,"model":"3d-felix-20-assembled-single","image":null,"dimensions":{"x":null,"y":null,"z":null}},{"id":984,"name":"3D Felix 2.0 Kit Dual","brand":null,"automatic_slicing":null,"nozzle_diameter":null,"premium":false,"model":"3d-felix-20-kit-dual","image":null,"dimensions":{"x":null,"y":null,"z":null}},{"id":981,"name":"3D Felix 2.0 Kit Single","brand":null,"automatic_slicing":null,"nozzle_diameter":null,"premium":false,"model":"3d-felix-20-kit-single","image":null,"dimensions":{"x":null,"y":null,"z":null}},{"id":989,"name":"3D Felix 3.0 Assembled Dual","brand":null,"automatic_slicing":null,"nozzle_diameter":null,"premium":false,"model":"3d-felix-30-assembled-dual","image":null,"dimensions":{"x":null,"y":null,"z":null}},{"id":986,"name":"3D Felix 3.0 Assembled Single","brand":null,"automatic_slicing":null,"nozzle_diameter":null,"premium":false,"model":"3d-felix-30-assembled-single","image":null,"dimensions":{"x":null,"y":null,"z":null}},{"id":983,"name":"3D Felix 3.0 Kit Dual","brand":null,"automatic_slicing":null,"nozzle_diameter":null,"premium":false,"model":"3d-felix-30-kit-dual","image":null,"dimensions":{"x":null,"y":null,"z":null}},{"id":657,"name":"3D Felix 3.0 Kit Single","brand":null,"automatic_slicing":null,"nozzle_diameter":null,"premium":false,"model":"3d-felix-30-kit-single","image":null,"dimensions":{"x":null,"y":null,"z":null}},{"id":992,"name":"3D Felix Pro 1","brand":null,"automatic_slicing":null,"nozzle_diameter":null,"premium":false,"model":"3d-felix-pro-1","image":null,"dimensions":{"x":null,"y":null,"z":null}},{"id":959,"name":"3D Pen","brand":null,"automatic_slicing":null,"nozzle_diameter":null,"premium":false,"model":"3d-pen","image":null,"dimensions":{"x":null,"y":null,"z":null}},{"id":714,"name":"3D Printer CB-printer KIT","brand":null,"automatic_slicing":null,"nozzle_diameter":null,"premium":false,"model":"3d-printer-cb-printer-kit","image":null,"dimensions":{"x":null,"y":null,"z":null}},{"id":942,"name":"3D Scanner HD","brand":null,"automatic_slicing":null,"nozzle_diameter":null,"premium":false,"model":"3d-scanner-hd","image":null,"dimensions":{"x":null,"y":null,"z":null}},{"id":832,"name":"3D Stuffmaker Prusa Gen 2","brand":null,"automatic_slicing":null,"nozzle_diameter":null,"premium":false,"model":"3d-stuffmaker-prusa-gen-2","image":null,"dimensions":{"x":null,"y":null,"z":null}},{"id":1031,"name":"3D Systems Projet 3500 HD Plus","brand":null,"automatic_slicing":null,"nozzle_diameter":null,"premium":false,"model":"3d-systems-projet-3500-hd-plus","image":null,"dimensions":{"x":null,"y":null,"z":null}},{"id":562,"name":"3D Systems ProJet 660","brand":null,"automatic_slicing":null,"nozzle_diameter":null,"premium":false,"model":"3d-systems-projet-660","image":null,"dimensions":{"x":null,"y":null,"z":null}},{"id":1030,"name":"3D Systems ProX 500","brand":null,"automatic_slicing":null,"nozzle_diameter":null,"premium":false,"model":"3d-systems-prox-500","image":null,"dimensions":{"x":null,"y":null,"z":null}},{"id":756,"name":"3D-One","brand":null,"automatic_slicing":null,"nozzle_diameter":null,"premium":false,"model":"3d-one","image":null,"dimensions":{"x":null,"y":null,"z":null}}]}
`

(I'm getting the same response when poking the API directly)
 I also have quite a few errors in the browser console. Here's a pic :
![capture](https://user-images.githubusercontent.com/8696690/50358234-e5ab9900-0558-11e9-92af-99b30f918901.PNG)

Thanks

**Comment by jneilliii** [comment]
More than likely on their end. You only see the printer list because that is info logged. If you enable debug logging in the logging  settings of octoprint for the plugin you will get a lot more info in octoprint.log.

**Comment by romainbou** [comment]
Hi @slock83 were you setting up the plugin for the first time?
The API seems ok on our end. I'll have a look tomorrow.
Thanks

**Comment by slock83** [comment]
Yes, I was setting it up for the first time.

Let me know if I can help, or provide anything.

Also : I was already on debug level, this is the only line that appears

**Comment by jneilliii** [comment]
Yeah, I just checked @slock83, and my installation is also able to pull a QR code without issue.  The one thing that we may need to take into account is where you are accessing the internet from geographically and if Google APIs are blocked for you or not?

**Comment by slock83** [comment]
@jneilliii yes, my settings are like this.

I am in France, never had an issue with anything blocked.

I will try from a fresh install if I have enough time

**Comment by romainbou** [comment]
It seems that this version isn't only fetching the compatible printers from the MyMiniFactory API. Adding the filter for compatibles printers fixes the issue for me.
It's possible that some fields are were missing in the unfiltered list making the plugin crash. I'll have a look at that later.
Here I made the fix: #8

**Comment by jneilliii** [comment]
I've made the api call adjustment that you suggested, but iterated version number to 0.1.1 as that is the next available release version.  You must have 0.1.1 from the development branch we were working on for larger files, pause related issues, etc.  @slock83 you should be able to upgrade from OctoPrint to this 0.1.1 version and verify for us if it works for you now or not.

**Comment by slock83** [comment]
Ok, will do. I can also update directly from a branch if you prefer not bumping the version everytime.

I have a print running, will update when it's finished

**Comment by slock83** [comment]
![capture](https://user-images.githubusercontent.com/8696690/50418552-445c6580-082c-11e9-8a90-60ff9653d20e.PNG)
Perfect, working now !

Thank you for your support :)
