### ISSUE TITLE
ImportError: Cannot import name version

### ISSUE THREAD

**Issue by ctluciani** [jneilliii/OctoPrint-MyMiniFactory#9]
I'm receiving this error when attempting to install the plugin. It happens both when installing via plugin manager, and when manually entering the github link. It told me the installation is successful, but I don't see the MyMiniFactory settings, and when I checked my console this is what happened.

I'm running Octoprint 1.3.5

**Comment by jneilliii** [comment]
I've only tested on 1.3.6 and above.  Any reason you aren't upgrading OctoPrint?

**Comment by ctluciani** [comment]
Just laziness! I will update and let you know what happens.

**Comment by ctluciani** [comment]
Updated and it's working like a charm! Thank you!
